[workspace]

members = [
  "postgres-role-json-pool",
  "postgres-transaction-pool",
  "postgres-services",
  "postgres-pool",
  "postgrpc",
  "postguard",
  "postrust"
]

[profile.release]
debug = true
codegen-units = 1
lto = "fat"
panic = "abort"
