[package]
name = "postgrpc"
version = "0.1.0"
authors = ["Alex Pearson <alex@platter.dev>"]
edition = "2021"
description = "A JSON-transcoding-ready gRPC server for querying Postgres"

[build-dependencies]
tonic-build = "0.8.0"

[dependencies]
envy = "0.4.2"
futures-util = "0.3.21"
prost = "0.11.0"
prost-types = "0.11.1"
serde_json = "1.0.83"
thiserror = "1.0.32"
tokio-stream = "0.1.9"
tonic-reflection = "0.5.0"
tracing = "0.1.36"
tracing-futures = "0.2.5"
uuid = "1.1.2"

# TODO:
# - split postgrpc and postgrpc-lib (i.e. a tower layer)
# - consolidate most of these workspace items into postgrpc-lib

[dependencies.postgres-pool]
path = "../postgres-pool"

[dependencies.postgres-role-json-pool]
path = "../postgres-role-json-pool"

[dependencies.postgres-services]
path = "../postgres-services"

[dependencies.postgres-transaction-pool]
optional = true
path = "../postgres-transaction-pool"

[dependencies.tokio]
default-features = false
features = ["macros", "signal", "rt-multi-thread"]
version = "1.20.1"

[dependencies.tonic]
default-features = false
features = ["codegen", "prost", "transport"]
version = "0.8.0"

[dependencies.tower-http]
default-features = false
features = ["trace"]
version = "0.3.4"

[dependencies.tracing-subscriber]
features = ["env-filter"]
version = "0.3.15"

[features]
default = ["transaction", "ssl-native-tls", "role-header"]
transaction = ["postgres-transaction-pool", "postgres-services/transaction"]
ssl-native-tls = ["postgres-role-json-pool/ssl-native-tls"]
role-header = []

# TODO: features
# - connection pooling (choose between implementations... custom? or deadpool et al?)
# - channels (enable LISTEN + NOTIFY based channels)
# - json (enable native JSON transcoding)
# - lib-features: valuable support
