[package]
name = "postgrpc"
version = "0.1.0"
authors = ["Alex Pearson <alex@platter.dev>"]
edition = "2018"
description = "A JSON-transcoding-ready gRPC server for querying Postgres"

[build-dependencies]
tonic-build = "0.5.2"

[dependencies]
envy = "0.4.2"
futures-util = "0.3.17"
prost = "0.8.0"
prost-types = "0.8.0"
serde_json = "1.0.68"
thiserror = "1.0.29"
tokio-stream = "0.1.7"
tonic-reflection = "0.2.0"
tracing = "0.1.26"
tracing-subscriber = "0.2.18"
tracing-futures = "0.2.5"
uuid = "0.8.2"

[dependencies.http]
optional = true
version = "0.2"

[dependencies.http-body]
optional = true
version = "0.4.2"

[dependencies.hyper]
optional = true
features = ["full"]
version = "0.14.13"

[dependencies.postgres-pool]
path = "../postgres-pool"

[dependencies.postgres-role-json-pool]
features = ["http-types"]
path = "../postgres-role-json-pool"

[dependencies.postgres-services]
path = "../postgres-services"

[dependencies.postgres-transaction-pool]
optional = true
path = "../postgres-transaction-pool"

[dependencies.tokio]
default-features = false
features = ["macros", "signal", "rt-multi-thread"]
version = "1.6.1"

[dependencies.tonic]
default-features = false
features = ["codegen", "prost", "transport"]
version = "0.5.2"

[dependencies.tower]
optional = true
version = "0.4.9"

[dependencies.tower-http]
default-features = false
features = ["trace"]
version = "0.1.1"

[features]
default = ["transaction", "ssl-native-tls", "role-header", "json-transcoding"] # FIXME: disable transcoding by default
transaction = ["postgres-transaction-pool", "postgres-services/transaction"]
ssl-native-tls = ["postgres-role-json-pool/ssl-native-tls"]
json-transcoding = ["http", "http-body", "hyper", "postgres-services/http-service", "tower"]
role-header = []

# TODO: features
# - connection pooling (choose between implementations)
