[package]
name = "postrust"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.29"
tracing = "0.1.29"
tracing-futures = "0.2.5"
tracing-subscriber = "0.2.25"
envy = "0.4.2"
bytes = "1.1.0"
byteorder = "1.4.3"
memchr = "2.4.1"
postgres-protocol = "0.6.2"
futures-core = "0.3.17"
fallible-iterator = "0.2.0"
futures-util = "0.3.17"
 
[dependencies.serde]
features = ["derive"]
version = "1.0.126"

[dependencies.tokio]
default-features = false
features = ["net", "macros", "rt-multi-thread", "signal", "io-util"]
version = "1.6.1"

[dependencies.tokio-util]
features = ["codec"]
version = "0.6.8"
