version: "3.7"

services:
  kratos-migrate:
    image: oryd/kratos:v0.7.4-alpha.1-sqlite
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.7.4-alpha.1-sqlite
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    networks:
      - intranet

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - intranet

  # auth-app:
  #   build:
  #     context: ./app
  #   ports:
  #     - "4455:4455"
  #   environment:
  #     - PORT=4455
  #     - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
  #     - KRATOS_PUBLIC_URL=http://kratos:4433/
  #     - KRATOS_ADMIN_URL=http://kratos:4434/
  #   networks:
  #     - intranet
  #   restart: on-failure
  postgrpc:
    build:
      context: ../../../
      dockerfile: postgrpc/Dockerfile
    depends_on:
      - postgres
    ports:
      - "50051:50051"
    environment:
      - HOST=0.0.0.0
      - PGHOST=postgres
      - PGDBNAME=appdb
      - PGUSER=appuser
      - PGPASSWORD=supersecretpassword
      - RUST_LOG=info
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=superuserpassword
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh

  # TODO:
  # include oathkeeper proxy in front of postgrpc
  # write custom "secureapp" that:
  # - doesn't include the entire recovery flow/email confirmation
  # - creates new postgres users for application users
  # - allows users to CRUD their own notes
  # BONUS: use registered queries for extra security

networks:
  intranet:

volumes:
  kratos-sqlite:

